apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dhkeys.xenit.io
spec:
  group: xenit.io
  names:
    kind: DHKey
    listKind: DHKeyList
    plural: dhkeys
    singular: dhkey
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                key_size:
                  type: integer
      served: true
      storage: true
      subresources:
        status: {}
