apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dhkeys.dhkey.xenit.io
spec:
  group: dhkey.xenit.io
  names:
    kind: DHKey
    listKind: DHKeyList
    plural: dhkeys
    singular: dhkey
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
