---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhkey-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: dhkey-operator
  template:
    metadata:
      labels:
        name: dhkey-operator
    spec:
      serviceAccountName: dhkey-operator
      containers:
        - name: dhkey-operator
          image: "quay.io/xenitab/dhkey-operator:v0.0.1-alpha2"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "dhkey-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
          livenessProbe:
            httpGet:
              path: /healthz
              port: 6789
            initialDelaySeconds: 5
            periodSeconds: 3
      volumes:
        - name: runner
          emptyDir: {}
