---
# tasks file for dhkey
- name: Get DHKey if already exists
  k8s_info:
    api_version: v1
    kind: Secret
    namespace: "{{ meta.namespace }}"
    label_selectors:
      - name = "{{ meta.name }}-dhkey"
      - type = dhkey
  register: dhSecret

- name: Generate DHKey if not exists
  openssl_dhparam:
    path: "/tmp/{{ meta.name }}-dhkey.pem"
    size: '{{ key_size }}'
  when: dhSecret.resources == []

- name: Create k8s secret for cpx-ingress
  k8s:
    namespace: "{{ meta.namespace }}"
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: "{{ meta.name }}-dhkey"
        labels:
          name: "{{ meta.name }}-dhkey"
          type: dhkey
      data:
        dhKey: "{{lookup('file', '/tmp/{{ meta.name }}-dhkey.pem') | b64encode }}"
  when: dhSecret.resources == []