{{- if .Values.operator.clusterScoped }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dhkey-operator
subjects:
- kind: ServiceAccount
  name: dhkey-operator
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: dhkey-operator
  apiGroup: rbac.authorization.k8s.io
{{- end }}
