{{- if not .Values.operator.clusterScoped }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dhkey-operator
subjects:
- kind: ServiceAccount
  name: dhkey-operator
roleRef:
  kind: Role
  name: dhkey-operator
  apiGroup: rbac.authorization.k8s.io
{{- end }}
